name: manual-workflow

on: 
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Choose enviroment"
        type: choice
        required: true
        default: "staging"
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "deploying the application to ${{inputs.enviroment}}"
